- name: Update Managed Hosts
  hosts: managedhosts
  remote_user: ec2-user

  vars_prompt:

  - name: trello_api_key
    prompt: Enter your Trello API key..
  
  - name: trello_api_token
    prompt: Enter your Trello API Token..

  tasks:
  - name: Install Git
    ansible.builtin.yum:
      name: git
      state: latest
    become: yes

  - name: Install Python3
    ansible.builtin.yum:
      name: python3
      state: latest
    become: yes

  - name: Install Poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: /home/ec2-user/.local/bin/poetry

  - name: Create todoapp Directory
    ansible.builtin.shell: mkdir /opt/todoapp
    args:
      creates: /opt/todoapp
    become: yes
    
  - name: Change folder owner to ec2-user
    ansible.builtin.shell: chown ec2-user /opt/todoapp
    become: yes

  - name: Checkout Git Repo Exercise 4
    ansible.builtin.git:
      repo: 'https://github.com/michaelhorsler/DevOps-Course-Starter.git'
      dest: /opt/todoapp
      version: exercise-4

  - name: Install Python Dependancies
    ansible.builtin.shell: poetry install
    args:
      chdir: /opt/todoapp

  - name: Copy .env file from template file
    ansible.builtin.template:
      src: /home/ec2-user/.env.j2
      dest: /opt/todoapp/.env

  - name: Copy todo app service definition file
    ansible.builtin.copy:
      src: /home/ec2-user/todoapp.service
      dest: /etc/systemd/system/todoapp.service
    become: yes

  - name: Make sure a service unit is running
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: todoapp.service
    become: yes