name: Continuous Integration
on: 
  pull_request:
    types: 
      - opened
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --entrypoint poetry todo-app:test run safety check
      continue-on-error: true
    - run: docker run todo-app:test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - run: echo Publishing!
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      

      -
        name: Build and Push Production to Docker Hub
        uses: actions/checkout@v4
      - run: docker build --target production --tag michaelsminis/todo-app:latest .
      - run: docker push michaelsminis/todo-app:latest
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: curl -dH -X POST "$(terraform output -raw webhook_url)"
      
